# Generated by Django 5.2.6 on 2025-10-04 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adm_no', models.IntegerField()),
                ('stu_name', models.CharField(max_length=100)),
                ('stu_email', models.EmailField(max_length=100)),
                ('stu_branch', models.CharField(max_length=100)),
                ('stu_sem', models.CharField(max_length=100)),
                ('stu_year', models.CharField(max_length=100)),
                ('stu_dob', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
