# Generated by Django 5.2.6 on 2025-10-04 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doubtstack', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginDB',
        ),
    ]
