# Generated by Django 5.2.6 on 2025-10-04 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doubtstack', '0002_delete_logindb'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginDB',
            fields=[
                ('adm_no', models.IntegerField(primary_key=True, serialize=False)),
                ('stu_name', models.CharField(max_length=100)),
                ('stu_email', models.EmailField(max_length=100)),
                ('stu_branch', models.CharField(max_length=100)),
                ('stu_start_year', models.IntegerField()),
                ('stu_end_year', models.IntegerField()),
                ('stu_dob', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
