# Generated by Django 5.2.6 on 2025-10-04 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doubtstack', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginDB2',
            fields=[
                ('tchr_no', models.IntegerField(primary_key=True, serialize=False)),
                ('tchr_name', models.CharField(max_length=100)),
                ('tchr_email', models.EmailField(max_length=100)),
                ('tchr_dept', models.CharField(max_length=100)),
                ('tchr_role', models.CharField(max_length=100)),
                ('tchr_join_year', models.IntegerField()),
                ('tchr_dob', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
