# Generated by Django 5.2.6 on 2025-10-04 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doubtstack', '0004_logindb2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginDB',
        ),
        migrations.DeleteModel(
            name='LoginDB2',
        ),
    ]
