# Generated by Django 5.2.6 on 2025-10-04 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doubtstack', '0006_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginDB',
        ),
        migrations.DeleteModel(
            name='LoginDB2',
        ),
        migrations.DeleteModel(
            name='OTPVerification',
        ),
        migrations.DeleteModel(
            name='UserAccount',
        ),
    ]
