# Generated by Django 5.2.6 on 2025-10-04 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doubtstack', '0008_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginDB',
        ),
        migrations.DeleteModel(
            name='LoginDB2',
        ),
        migrations.DeleteModel(
            name='OTP',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
