# Generated by Django 5.2.6 on 2025-10-04 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doubtstack', '0009_delete_logindb_delete_logindb2_delete_otp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginDB',
            fields=[
                ('adm_no', models.IntegerField(primary_key=True, serialize=False)),
                ('stu_name', models.CharField(max_length=100)),
                ('stu_email', models.EmailField(max_length=100)),
                ('stu_branch', models.CharField(max_length=100)),
                ('stu_sem', models.IntegerField(default=1)),
                ('stu_start_year', models.CharField(max_length=100)),
                ('stu_end_year', models.CharField(max_length=100)),
                ('stu_dob', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoginDB2',
            fields=[
                ('tchr_no', models.IntegerField(primary_key=True, serialize=False)),
                ('tchr_name', models.CharField(max_length=100)),
                ('tchr_email', models.EmailField(max_length=100)),
                ('tchr_dept', models.CharField(max_length=100)),
                ('tchr_role', models.CharField(max_length=100)),
                ('tchr_join_year', models.IntegerField()),
                ('tchr_dob', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.IntegerField()),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=30)),
                ('semester', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=30)),
                ('role', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
