# Generated by Django 5.2.6 on 2025-10-06 18:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doubtstack', '0010_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='doubtstack.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Doubt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('topic', models.CharField(blank=True, max_length=255, null=True)),
                ('text', models.TextField()),
                ('anonymous', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('unresolved', 'Unresolved'), ('resolved', 'Resolved'), ('escalated', 'Escalated')], default='unresolved', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_doubts', to='doubtstack.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doubtstack.subject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doubt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='doubtstack.doubt')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doubt_votes', to='doubtstack.student')),
            ],
            options={
                'unique_together': {('doubt', 'student')},
            },
        ),
    ]
