# Generated by Django 5.2.6 on 2025-10-07 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doubtstack', '0011_subject_doubt_vote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('reply_id', models.AutoField(primary_key=True, serialize=False)),
                ('reply_text', models.CharField(blank=True, max_length=1000, null=True)),
                ('file_url', models.FileField(blank=True, null=True, upload_to='replies/')),
                ('anonymous', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doubt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='doubtstack.doubt')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doubtstack.student')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doubtstack.teacher')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
