# Generated by Django 5.2.6 on 2025-10-10 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doubtstack', '0012_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='reply_type',
            field=models.CharField(choices=[('text', 'Text'), ('file', 'File'), ('audio', 'Audio'), ('video', 'Video'), ('whiteboard', 'Whiteboard')], default='text', max_length=20),
        ),
    ]
